CREATE TABLE restaurants (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    r_name VARCHAR(50) NOT NULL UNIQUE,
    r_password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
